### ISSUE TITLE
Commiting package.json

### ISSUE THREAD

**Issue by shadowtime2000** [nastyox/Rando.js#12]
It is considered a good practice when creating a package to commit the `package.json`. It allows people to contribute to stuff on their and for people to look at the details that may not be able to be viewed on the `npm` website.

**Comment by nastyox** [comment]
When I install Rando.js with `npm i @nastyox/rando.js`, I get the `package.json`. Is there something I'm misunderstanding? If so, let me know, and I'll be happy to help.
![Rando.js files](http://randojs.com/images/extra/package-json.png)

**Comment by shadowtime2000** [comment]
When you run `npm i @nastyox/rando.js` the `package.json` and other files for the NodeJS version are put inside the `node_modules` folder  which isn't really what I mean. I am saying that you should commit the `package.json` along with the NodeJS version to make it more transparent, because currently the only basic browser version is commited, so it is hard to find what you are downloading when running `npm i @nastyox/rando.js`.

**Comment by nastyox** [comment]
Thanks for the clarification! I'll have a look at this and close this issue out once it's resolved or post here again if for some reason I need further clarification. Thanks for your interaction with the project!

**Comment by shadowtime2000** [comment]
> Thanks for the clarification! I'll have a look at this and close this issue out once it's resolved or post here again if for some reason I need further clarification. Thanks for your interaction with the project!

@nastyox I would also recommend you move the browser files to a `browser` folder and keep the node files in a `node` folder.

**Comment by nastyox** [comment]
It took me so long to figure out you were talking about committing `package.json` _to this GitHub repo_. I thought you wanted me to add some sort of extra `package.json` file to the npm package and couldn't figure out what on earth you were talking about. This is complete. Thanks for the suggestion!
