### ISSUE TITLE
Expired certificate on https://randojs.com

### ISSUE THREAD

**Issue by birtony** [nastyox/Rando.js#16]
@nastyox looks like #15 has happened again. Could you, please, take action to unblock the users?

**Comment by nastyox** [comment]
Developers shouldn't have to deal with this, so thank you for taking the time to create this issue. I've take 3 steps to rectify this:
1. I've renewed our SSL.
2. I've forwarded reminder notifications to an email address where I'll absolutely see them next time- not my spam email address.
3. I've moved the rando.js script onto a CDN, which will remain stable. That way you don't have to trust me to keep up with anything.

Again, thank you so much for getting in touch and helping correct issue this for everyone.
