### ISSUE TITLE
Will Rando.js be released on NPM ?

### ISSUE THREAD

**Issue by DaniGTA** [nastyox/Rando.js#3]
NPM = https://www.npmjs.com/

I use a Framework for my website and i import everything that i need via npm. 
It would be nice if Rando.js will be available on npm.

**Comment by nastyox** [comment]
Thank you for the feedback. I'll address that this weekend.

**Comment by nastyox** [comment]
This is ready!

**Comment by nastyox** [comment]
Hi DaniGTA. Rando.js was working improperly on Node.js for a bit. If you would like to reinstall the latest version, that has been corrected.
