### ISSUE TITLE
can be used to decrypt and encrypt using js ?

### ISSUE THREAD

**Issue by yezz123** [nastyox/Rando.js#7]

**Comment by nastyox** [comment]
Thanks for your interest in this project! If you are trying to come up with a secret passphrase to use with an encryption algorithm, Rando.js has enough entropy to be safely used for password generation. However, as far as actually encrypting a string goes, this micro-library will not do that for you. I'm not sure that encryption functionality suits the purpose of Rando.js overwhelmingly well, so I am not currently considering adding it to the project. I will be happy to reconsider if this request is largely supported. Until then, perhaps you should check out aes-js. Again, thank you for interacting with this project, and I hope to see you around here in the future. Have a good one!
