### ISSUE TITLE
rando(5) return false

### ISSUE THREAD

**Issue by kirit0s** [nastyox/Rando.js#8]
![image](https://user-images.githubusercontent.com/14249148/89634348-e5871b00-d8ad-11ea-8095-01517642909d.png)

Only `rando()` work fine.

What about any tests?

**Comment by nastyox** [comment]
Thank you very much for bringing this to my attention. Please use version 2.0.1 and note that it does not include jQuery compatibility.

**Comment by nastyox** [comment]
This will be the last time I comment here. I just want to thank you again for raising this issue and let you know that I released version 2.0.2 today, which includes jQuery compatibility and built-in module testing.
